Repository DhanushNehru/Ultimate-Web-Development-Resources, pull requests merged in 2022-10, with the labels that each got.

#13 added free illustrations resource for web design
  README.md
Labels: documentation, hacktoberfest

#15 feat: Add fusioncharts
  README.md
Labels: documentation, hacktoberfest

#24 codeforces link added
  README.md
Labels: documentation, good first issue, hacktoberfest

#47 Added Animations & Graphics Libraries
  README.md
Labels: hacktoberfest

#55 Added a new section of Chrome Extension For Web Developer
  README.md
Labels: hacktoberfest

#58 Added a resource for web development-
  README.md
Labels: documentation, hacktoberfest

#67 Added New Category and Links
  README.md
Labels: hacktoberfest

#74 Added Top React component Libraries Kindly merge it
  README.md
Labels: hacktoberfest
